package GUI;
import tgid_teste.ConnectionDB;


/**
 *
 * @author WIN10
 */
public class Login_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Login_Screen
     */
    public Login_Screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logo1 = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        userLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        enterBTN = new javax.swing.JButton();
        clientRadio = new javax.swing.JRadioButton();
        companyRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(0, 153, 153));

        logo1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        logo1.setForeground(new java.awt.Color(102, 255, 204));
        logo1.setText("Sistema de Transações");

        logo2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 58)); // NOI18N
        logo2.setForeground(new java.awt.Color(102, 255, 204));
        logo2.setText("TGID");

        userField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        userField.setToolTipText("");

        passwordField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        passwordField.setPreferredSize(new java.awt.Dimension(150, 40));

        userLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        userLabel.setForeground(new java.awt.Color(102, 255, 204));
        userLabel.setText("CPF ou CNPJ (com pontos e barra):");

        passwordLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(102, 255, 204));
        passwordLabel.setText("Senha:");

        enterBTN.setBackground(new java.awt.Color(102, 255, 204));
        enterBTN.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        enterBTN.setText("Entrar");
        enterBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBTNActionPerformed(evt);
            }
        });

        clientRadio.setBackground(new java.awt.Color(0, 153, 153));
        clientRadio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        clientRadio.setForeground(new java.awt.Color(102, 255, 204));
        clientRadio.setText("Cliente");
        clientRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientRadioActionPerformed(evt);
            }
        });

        companyRadio.setBackground(new java.awt.Color(0, 153, 153));
        companyRadio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        companyRadio.setForeground(new java.awt.Color(102, 255, 204));
        companyRadio.setText("Empresa");
        companyRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(logo1)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(companyRadio)
                            .addComponent(clientRadio))
                        .addGap(388, 388, 388))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userLabel)
                            .addComponent(passwordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logo2)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(enterBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(logo1)
                .addGap(18, 18, 18)
                .addComponent(logo2)
                .addGap(73, 73, 73)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(18, 18, 18)
                .addComponent(enterBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clientRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(companyRadio)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        logo1.getAccessibleContext().setAccessibleName("logo1");
        logo2.getAccessibleContext().setAccessibleName("logo2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientRadioActionPerformed
        companyRadio.setSelected(false);
    }//GEN-LAST:event_clientRadioActionPerformed

    private void companyRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyRadioActionPerformed
        clientRadio.setSelected(false);
    }//GEN-LAST:event_companyRadioActionPerformed

    private void enterBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBTNActionPerformed
        ConnectionDB con = new ConnectionDB();
        String user = userField.getText();
        String password = new String(passwordField.getPassword());
        String type = "";
        String identification = "";
        
        if(clientRadio.isSelected()) {
            type = "client";
        } 
        if(companyRadio.isSelected()) {
           type = "company";
        }
        identification = con.Login(user, password, type);
        
        if(!identification.equals("None")) {
            if(clientRadio.isSelected()) {
                GUI.ClientScreens.Main_Screen client_ms = new GUI.ClientScreens.Main_Screen(identification);
                client_ms.setVisible(true);
                dispose();
            }
            if(companyRadio.isSelected()) {
                GUI.CompanyScreens.Main_Screen company_ms = new GUI.CompanyScreens.Main_Screen(identification);
                company_ms.setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_enterBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JRadioButton clientRadio;
    private javax.swing.JRadioButton companyRadio;
    private javax.swing.JButton enterBTN;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
