/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.CompanyScreens;

import java.util.ArrayList;
import tgid_teste.ConnectionDB;

/**
 *
 * @author WIN10
 */
public class Main_Screen extends javax.swing.JFrame {
    ArrayList<Object> clientData;
    public Main_Screen() {
        initComponents();
    }
    
    public Main_Screen(String cnpj) {
        ConnectionDB con = new ConnectionDB();
        
        
        initComponents();
        clientData = con.data(cnpj, "company");
        companyName.setText(String.valueOf(clientData.get(0)));
        cnpjNumber.setText(cnpj);
        amountField.setText(String.valueOf(clientData.get(1)));
        taxField.setText(String.valueOf(clientData.get(2)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        taxLabel = new javax.swing.JLabel();
        taxField = new javax.swing.JTextField();
        companyLabel = new javax.swing.JLabel();
        companyName = new javax.swing.JLabel();
        saveBTN = new javax.swing.JButton();
        cnpjNumber = new javax.swing.JLabel();
        companyLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(0, 153, 153));

        welcome.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        welcome.setForeground(new java.awt.Color(102, 255, 204));
        welcome.setText("Bem Vindo");

        amountLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        amountLabel.setForeground(new java.awt.Color(102, 255, 204));
        amountLabel.setText("Saldo Atual da Empresa:");

        amountField.setEditable(false);
        amountField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        amountField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });

        taxLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        taxLabel.setForeground(new java.awt.Color(102, 255, 204));
        taxLabel.setText("Taxa de Sistema da Empresa:");

        taxField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        taxField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        taxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxFieldActionPerformed(evt);
            }
        });

        companyLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        companyLabel.setForeground(new java.awt.Color(102, 255, 204));
        companyLabel.setText("Nome da Empresa:");

        companyName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        companyName.setForeground(new java.awt.Color(102, 255, 204));
        companyName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        companyName.setText("Nome da Empresa");

        saveBTN.setBackground(new java.awt.Color(102, 255, 204));
        saveBTN.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        saveBTN.setText("Salvar Alterações");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        cnpjNumber.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        cnpjNumber.setForeground(new java.awt.Color(102, 255, 204));
        cnpjNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cnpjNumber.setText("00.000.000/0000-00");

        companyLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        companyLabel1.setForeground(new java.awt.Color(102, 255, 204));
        companyLabel1.setText("CNPJ:");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(welcome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(companyLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cnpjNumber))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(companyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(companyName, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(amountLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taxLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taxField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(saveBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(welcome)
                .addGap(36, 36, 36)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyLabel)
                    .addComponent(companyName))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cnpjNumber)
                    .addComponent(companyLabel1))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLabel)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxLabel)
                    .addComponent(taxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void taxFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxFieldActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        ConnectionDB con = new ConnectionDB();
        try {
            if(con.ChangeTax(Double.valueOf(taxField.getText()), cnpjNumber.getText()) == false) {
                taxField.setText(String.valueOf(clientData.get(2)));
            }
        } catch(NumberFormatException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_saveBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JPanel background;
    private javax.swing.JLabel cnpjNumber;
    private javax.swing.JLabel companyLabel;
    private javax.swing.JLabel companyLabel1;
    private javax.swing.JLabel companyName;
    private javax.swing.JButton saveBTN;
    private javax.swing.JTextField taxField;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
